function testProjectionAxes
% TESTPROJECTIONAXES Testing projection axes on both sides of a 2D plot.
%
% Usage
%   testProjectionAxes

% Copyright (c) 2014, Till Biskup
% 2014-10-16

defaultBackground = [.9 .9 .9];
dx = 20;
dy = 40;

% Define main GUI window (figure)
hMainFigure = figure('Tag',mfilename,...
    'Name','trEPR GUI : Main Window',...
    'Units','Pixels',...
    'Position',[dx,dy,950,700],...
    'Resize','off',...
    'NumberTitle','off', ...
    'Menu','none','Toolbar','none',...
    'Color',defaultBackground...
);


% Create the main axis
% The mainAxes_panel contains all the axis-related ui elements
hPanelAxis = uipanel('Tag','mainAxes_panel',...
    'Parent',hMainFigure,...
    'Units','pixels',...
    'Position',[0,75,650,630],...
    'Title','',...
    'BorderType','none',...
    'BackgroundColor',defaultBackground,...
    'Visible','on'...
);

hPlotAxes = axes(...         % axes for plotting selected plot
    'Tag','mainAxis',...
	'Parent', hPanelAxis, ...
    'FontUnit','Pixel','Fontsize',14,...
    'Units', 'Pixels', ...
    'Box','on',...
    'Position',[70 95 500 500]);

hHorizontalAxes = axes(...         % axes for horizontal projection
    'Visible','off',...
    'Tag','mainAxis',...
	'Parent', hPanelAxis, ...
    'FontUnit','Pixel','Fontsize',14,...
    'Units', 'Pixels', ...
    'Box','on',...
    'Position',[120 95 450 50]);

hVerticalAxes = axes(...         % axes for vertical projection
    'Visible','off',...
    'Tag','mainAxis',...
	'Parent', hPanelAxis, ...
    'FontUnit','Pixel','Fontsize',14,...
    'Units', 'Pixels', ...
    'Box','on',...
    'Position',[70 145 50 450]);

% Create the sliders
slider_scroll_bgcolor = [1.0 0.7 0.7];
slider_scale_bgcolor = [1.0 1.0 0.8];
slider_displace_bgcolor = [0.8 1.0 1.0];

uicontrol('Tag','vert1_slider',...
    'Style', 'slider',...
	'Parent', hPanelAxis, ...
    'Min',1,'Max',100,'Value',50,...
    'Position', [595 95 15 500],...
    'BackgroundColor',slider_scroll_bgcolor,...
    'TooltipString','Scroll through dataset along second axes'...
    );

uicontrol('Tag','vert2_slider',...
    'Style', 'slider',...
	'Parent', hPanelAxis, ...
    'Min',-1,'Max',1,'Value',0,...
    'Position', [615 95 15 500],...
    'BackgroundColor',slider_scale_bgcolor,...
    'TooltipString','Scale'...
    );

uicontrol('Tag','vert3_slider',...
    'Style', 'slider',...
	'Parent', hPanelAxis, ...
    'Min',-1,'Max',1,'Value',0,...
    'Position', [635 95 15 500],...
    'BackgroundColor',slider_displace_bgcolor,...
    'TooltipString','Displace'...
    );

uicontrol('Tag','horz1_slider',...
    'Style', 'slider',...
	'Parent', hPanelAxis, ...
    'Min',-1,'Max',1,'Value',0,...
    'Position', [70 20 500 15],...
    'BackgroundColor',slider_scale_bgcolor,...
    'TooltipString','Scale'...
    );

uicontrol('Tag','horz2_slider',...
    'Style', 'slider',...
	'Parent', hPanelAxis, ...
    'Min',-1,'Max',1,'Value',0,...
    'Position', [70 0 500 15],...
    'BackgroundColor',slider_displace_bgcolor,...
    'TooltipString','Displace'...
    );

uicontrol('Tag','toggleAxes_pushbutton',...
    'Style','pushbutton',...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[700 20 75 25],...
    'String','Toggle',...
    'TooltipString','<html>Toggle axes',...
    'Callback',{@pushbutton_Callback,'toggleAxes'}...
    );

xlabel(hPlotAxes,'time / s');
ylabel(hPlotAxes,'intensity / a.u.');

showProjection = false;
    
    function pushbutton_Callback(~,~,action)
        try
            switch lower(action)
                case 'toggleaxes'
                    if showProjection
                        set(hPlotAxes,'Position',[70 95 500 500]);
                        set(hHorizontalAxes,'Visible','off');
                        set(hVerticalAxes,'Visible','off');
                        set(hPlotAxes,'XTickLabelMode','auto');
                        xlabel(hPlotAxes,'time / s');
                        ylabel(hPlotAxes,'intensity / a.u.');
                        showProjection = false;
                    else
                        set(hPlotAxes,'Position',[120 145 450 450]);
                        set(hPlotAxes,'XTickLabel',{''});
                        set(hPlotAxes,'YTickLabel',{''});
                        set(hVerticalAxes,'XTickLabel',{''});
                        set(hHorizontalAxes,'YTickLabel',{''});
                        set(hHorizontalAxes,'Visible','on');
                        set(hVerticalAxes,'Visible','on');
                        xlabel(hHorizontalAxes,'time / s');
                        ylabel(hVerticalAxes,'intensity / a.u.');
                        xlabel(hPlotAxes,'');
                        ylabel(hPlotAxes,'');
                        showProjection = true;
                    end
                otherwise
                    trEPRoptionUnknown(action);
                    return;
            end
        catch exception
            trEPRexceptionHandling(exception)
        end
    end

end


