function conf = TsimConf(varargin)
% TSIMCONF Return configuration settings for simulating and fitting
% triplet spectra with Tsim.
%
% Usage
%   conf = TsimConf();
%
%   conf - struct
%          Structure containing the configuration settings for the
%          Tsim module
%
% See also TSIM

% Copyright (c) 2013-14, Deborah Meyer, Till Biskup
% 2015-05-22

% TODO: Read configuration from file

% For now, just create configuration structure and fill it manually
% IMPORTANT: Configuration settings are set (manually) only here!
gx = 2.002;
gy = 2.002;
gz = 2.002;
D = 760;    % in MHz (!)
E = 250;    % in MHz (!)
lwGauss = 2; 
lwLorentz = 2;


conf = struct(...
    'parameters',struct(...
        ), ...        
    'sim',struct(...
    
        'Sys',struct(...
            'S', 1,...
            'g', [gx gy gz],...
            'D',[-D/3+E, -D/3-E, 2*D/3],...
            'lw',[lwGauss lwLorentz],...
            'DStrain',[],...
            'gStrain',[]...
            ),...
        'Exp',struct(...
            'mwFreq', 9.70,...
            'Range',[280 410],...
            'nPoints',326,...
            'Temperature',[0.3 0.33 0.37], ...
            'Ordering',0 ...
            ),...
        'Opt',struct(...
             'nKnots',[31 0],...
             'Harmonic',0 ...
            ),...
        'routine','pepper' ...
        ),...
    'fit',struct(...
        'fitpar',struct(...
                 ),...
        'initialvalue',[], ...
        'finalvalue',[], ...        
        'lb',[], ...
        'ub',[], ...
        'fitcut',struct(...
             'cutpoints',[], ...
             'mutilatedData',[],...
             'mutilatedField',[],...
             'cuttedIndices',[]...
             ),...
        'fitopt',struct(...
            'MaxIter',1,...
            'MaxFunEval',[],...
            'TolFun',1.0e-10 ...
           ),...
        'routine','lsqcurvefit' ...
        ) ...
        );
   

% Normalize populations
conf.Exp.Temperature = conf.Exp.Temperature/sum(conf.Exp.Temperature);

end
