function message = TsimDisclaimerCitation
% TSIMDISCLAIMERCITATION Return message providing the citation to be used 
% if any results of this program will be included in a thesis or
% publication.
%
% Usage
%   message = TsimDisclaimerCitation;
%
% See also TSIM

% Copyright (c) 2020, Till Biskup
% 2020-12-14

message = [...
    '*****************************************************************\n'...
    '*                                                               *\n'...
    '* It is mandatory to cite the following reference if any result *\n' ...
    '* from this program will be part of a thesis or publication:    *\n' ...
    '*                                                               *\n'...
    '*  D. L. Meyer, F. Lombeck, S. Huettner, M. Sommer, T. Biskup   *\n'...
    '*  J. Phys. Chem. Lett. 2017, 8, 1677-1682                      *\n'...
    '*                                                               *\n'...
    '*****************************************************************\n'...
    ];

end