function TsimWelcomeMessage
% TSIMWELCOMEMESSAGE Print welcome message describing Tsim and giving some
% information about whom to acknowledge.
%
% Usage
%   TsimWelcomeMessage;
%
% See also TSIM

% Copyright (c) 2015, Deborah Meyer, Till Biskup
% 2015-06-22

info = TsimInfo();

message = {...
    '****************************************************************' ...
    ' '...
    'Welcome to Tsim - a CLI for conveniently simulating and fitting' ...
    '                  spin-polarised EPR spectra of triplet states.' ...
    ' '...
    'If you use this program, please don''t forget to acknowledge' ...
    'those who (actively) develop it:' ...
    ' '...
    ['    ' strJoin({info.maintainer.name},' and ')] ...
    ' '...
    'Furthermore, please acknowledge the author(s) of the simulation'...
    'routines (and cite appropriately if necessary). This information '...
    'will be displayed depending on the simulation routine chosen.' ...
    ' '...
    'Thank you for your kind cooperation. Enjoy using Tsim.'...
    ' '...
    '****************************************************************' ...
    };

cellfun(@(x)disp(x),message);

end