function TsimWelcomeMessage
% TSIMWELCOMEMESSAGE Print welcome message describing Tsim and giving some
% information about whom to acknowledge.
%
% Usage
%   TsimWelcomeMessage;
%
% See also TSIM

% Copyright (c) 2015-20, Deborah Meyer, Till Biskup
% 2020-12-14

info = TsimInfo();

message = {...
    '*****************************************************************' ...
    ' '...
    'Welcome to Tsim - a CLI for conveniently simulating and fitting' ...
    '                  spin-polarised EPR spectra of triplet states.' ...
    ' '...
    '*****************************************************************'...
    '*                                                               *'...
    '* It is mandatory to cite the following reference if any result *' ...
    '* from this program will be part of a thesis or publication:    *' ...
    '*                                                               *'...
    '*  D. L. Meyer, F. Lombeck, S. Huettner, M. Sommer, T. Biskup   *'...
    '*  J. Phys. Chem. Lett. 2017, 8, 1677-1682                      *'...
    '*                                                               *'...
    '*****************************************************************'...
    ' '...
    'Furthermore, please acknowledge the author(s) of the simulation'...
    'routines (and cite appropriately if necessary). This information '...
    'will be displayed depending on the simulation routine chosen.' ...
    ' '...
    'Thank you for your kind cooperation. Enjoy using Tsim.'...
    ' '...
    '*****************************************************************' ...
    };

cellfun(@(x)disp(x),message);

end